export const tags = {
  categories: [
    {
      concept: ['age_18_25'],
      disp: ['18-25 years old'],
      profileDisplay: ['18-25 years old'],
      profileEntry: 1,
      type: ['sxs'],
      sys: ['gen'],
    },
    {
      concept: ['age_26_45'],
      disp: ['26-45 years old'],
      profileDisplay: ['26-45 years old'],
      profileEntry: 1,
      type: ['sxs'],
      sys: ['gen'],
    },
    {
      concept: ['age_46_65'],
      disp: ['46-65 years old'],
      profileDisplay: ['46-65 years old'],
      profileEntry: 1,
      type: ['sxs'],
      sys: ['gen'],
    },
    {
      concept: ['age_66'],
      disp: ['65+ years old'],
      profileDisplay: ['65+ years old'],
      profileEntry: 1,
      type: ['sxs'],
      sys: ['gen'],
    },
    {
      concept: ['gender_m'],
      disp: ['male'],
      profileDisplay: ['Male'],
      profileEntry: 1,
      type: ['demo'],
      syn: ['male sex', 'man'],
      sys: ['gen'],
    },
    {
      concept: ['gender_f'],
      disp: ['female'],
      profileDisplay: ['Female'],
      profileEntry: 1,
      type: ['demo'],
      syn: ['female sex', 'women', 'woman'],
      sys: ['gen'],
    },
    {
      concept: ['gender_o'],
      disp: ['Other'],
      profileDisplay: ['Other'],
      profileEntry: 1,
      type: ['demo'],
      sys: ['gen'],
    },
    {
      concept: ['diabetes'],
      disp: ['diabetes mellitus (DM)'],
      profileDisplay: ['diabetes mellitus (DM)'],
      profileEntry: 1,
      assocMeds: ['insulin', 'metformin', 'glipizide', 'sitagliptin'],
      type: ['dx'],
      syn: ['diabetes', 'DM', 'T1DM', 'T2DM'],
      sys: ['endo'],
    },
    {
      concept: ['hypertension'],
      disp: ['hypertension'],
      profileDisplay: ['Hypertension (high blood pressure)'],
      profileEntry: 1,
      assocMeds: ['metoprolol', 'lasix', 'amlodipine', 'lisinopril'],
      type: ['dx'],
      syn: [
        'hypertension',
        'increased blood pressure',
        'systemic hypertension',
        'elevated bp',
        'elevated blood pressure',
      ],
      sys: ['cv'],
    },
    {
      concept: ['hyperlipidemia'],
      disp: ['hyperlipidemia'],
      profileDisplay: ['Hyperlipidemia (high cholesterol)'],
      profileEntry: 1,
      assocMeds: ['atorvastatin', 'simvastatin'],
      type: ['dx'],
      syn: ['high cholesterol', 'hypercholesterolemia', 'dysplipidemia'],
      sys: ['cv'],
    },
    {
      concept: ['obestiy'],
      disp: ['obesity'],
      profileDisplay: ['Obesity'],
      profileEntry: 1,
      assocMeds: [],
      type: ['dx'],
      syn: ['obese'],
      sys: ['gen'],
    },
    {
      concept: ['gerd'],
      disp: ['gastroesophageal reflux disease (GERD)'],
      profileDisplay: ['Gastroesophageal reflux disease (GERD)'],
      profileEntry: 1,
      assocMeds: ['omeprazole', 'famotidine'],
      type: ['dx'],
      syn: ['acid reflux'],
      sys: ['gi'],
    },
    {
      concept: ['depression'],
      disp: ['depression'],
      profileDisplay: ['Depression/Anxiety'],
      profileEntry: 1,
      assocMeds: ['sertraline', 'lorazapam', 'citalopram', 'escitalopram'],
      type: ['dx'],
      sys: ['neuro'],
    },
    {
      concept: ['cva'],
      disp: ['CVA/Stroke'],
      profileDisplay: ['Prior stroke (CVA)'],
      profileEntry: 1,
      assocMeds: ['aspirin', 'clopidogrel'],
      type: ['dx'],
      syn: ['stroke', 'cerebral vascular accident', 'cerebrovascular disease'],
      sys: ['neuro', 'cv'],
    },
    {
      concept: ['hypothyroidism'],
      disp: ['hypothyroidism'],
      profileDisplay: ['Hypothroidism (deficient thyroid hormone)'],
      profileEntry: 1,
      assocMeds: ['levothyroxine'],
      type: ['dx'],
      sys: ['endo'],
    },
    {
      concept: ['copd'],
      disp: ['COPD'],
      profileDisplay: ['Chronic obstructive pulmonary disease (COPD)'],
      profileEntry: 1,
      assocMeds: ['albuterol', 'advair'],
      sys: ['pulm'],
      type: ['dx'],
    },
    {
      concept: ['chf'],
      disp: ['congestive heart failure (CHF)'],
      profileDisplay: ['congestive heart failure (CHF)'],
      profileEntry: 1,
      assocMeds: ['lasix', 'ng'],
      type: ['dx'],
      syn: ['heart failure', 'HF'],
      sys: ['cv'],
    },
    {
      concept: ['cad'],
      disp: ['coronary artery disease (CAD)'],
      profileDisplay: ['coronary artery disease (CAD)'],
      profileEntry: 1,
      assocMeds: ['aspirin', 'metoprolol'],
      type: ['dx'],
      syn: [
        'cardiovascular disease',
        'ischemic heart disease',
        'cardiac disease',
      ],
      isa: ['cvDisease'],
      sys: ['cv'],
    },
    {
      concept: ['aspirin'],
      disp: ['aspirin'],
      profileDisplay: ['Aspirin'],
      type: ['med'],
      syn: ['asa'],
      sys: ['cv'],
    },
    {
      concept: ['albuterol'],
      disp: ['albuterol'],
      profileDisplay: ['albuterol (Proair)'],
      type: ['med'],
      isa: ['beta adrenergic', 'beta agonst'],
      sys: ['pulm'],
    },
    {
      concept: ['omeprazole'],
      disp: ['omeprazole'],
      profileDisplay: ['Omeprazole (Prilosec)'],
      type: ['med'],
      sys: ['gi'],
    },
    {
      concept: ['famotidine'],
      disp: ['famotidine'],
      profileDisplay: ['Famotidine (Pepcid)'],
      type: ['med'],
      sys: ['gi'],
    },
    {
      concept: ['furosemide'],
      disp: ['furosemide'],
      profileDisplay: ['Furosemide (Lasix)'],
      type: ['med'],
      syn: ['lasix'],
      sys: ['cv'],
    },
    {
      concept: ['levothyroxine'],
      disp: ['levothyroxine'],
      profileDisplay: ['Levothyroxine (Synthroid)'],
      type: ['med'],
      syn: ['synthroid'],
      sys: ['endo'],
    },
    {
      concept: ['ng'],
      disp: ['nitrates'],
      profileDisplay: ['Nitroglycerin (Nitro-Bid)'],
      type: ['med'],
      syn: ['nitro'],
      sys: ['cv'],
    },
    {
      concept: ['insulin'],
      disp: ['insulin'],
      profileDisplay: ['Insulin'],
      type: ['med'],
      syn: [''],
      sys: ['endo'],
    },
    {
      concept: ['metformin'],
      disp: ['metformin'],
      profileDisplay: ['Metformin (Glucophage)'],
      type: ['med'],
      sys: ['endo'],
    },
    {
      concept: ['glipizide'],
      disp: ['glipizide'],
      profileDisplay: ['Glipizide (Glucotrol)'],
      type: ['med'],
      sys: ['endo'],
    },
    {
      concept: ['sitagliptin'],
      disp: ['sitagliptin'],
      profileDisplay: ['Sitagliptin (Januvia)'],
      type: ['med'],
      sys: ['endo'],
    },
    {
      concept: ['metoprolol'],
      disp: ['metoprolol'],
      profileDisplay: ['Metoprolol (Lopressor)'],
      type: ['med'],
      sys: ['cv'],
    },
    {
      concept: ['amlodipine'],
      disp: ['amlodipine'],
      profileDisplay: ['Amlodipine (Norvasc)'],
      type: ['med'],
      sys: ['cv'],
    },
    {
      concept: ['lisinopril'],
      disp: ['lisinopril'],
      profileDisplay: ['Lisinopril (Prinivil)'],
      type: ['med'],
      sys: ['cv'],
    },
    {
      concept: ['atorvastatin'],
      disp: ['atorvastatin'],
      profileDisplay: ['Atorvastatin (Lipitor)'],
      type: ['med'],
      sys: ['cv'],
    },
    {
      concept: ['simvastatin'],
      disp: ['simvastatin'],
      profileDisplay: ['Simvastatin (Zocor)'],
      type: ['med'],
      sys: ['cv'],
    },
    {
      concept: ['clopidogrel'],
      disp: ['clopidogrel'],
      profileDisplay: ['Clopidogrel (Plavix)'],
      type: ['med'],
      sys: ['cv'],
    },
    {
      concept: ['clopidogrel'],
      disp: ['clopidogrel'],
      profileDisplay: ['Clopidogrel (Plavix)'],
      type: ['med'],
      sys: ['cv'],
    },
    {
      concept: ['sertraline'],
      disp: ['sertraline'],
      profileDisplay: ['Sertraline (Zoloft)'],
      type: ['med'],
      sys: ['pysch'],
    },
    {
      concept: ['lorazepam'],
      disp: ['lorazepam'],
      profileDisplay: ['Lorazepam (Ativan)'],
      type: ['med'],
      sys: ['pysch'],
    },
    {
      concept: ['citalopram'],
      disp: ['citalopram'],
      profileDisplay: ['Citalopram (Celexa)'],
      type: ['med'],
      sys: ['pysch'],
    },
    {
      concept: ['escitalopram'],
      disp: ['escitalopram'],
      profileDisplay: ['Escitalopram (Lexapro)'],
      type: ['med'],
      sys: ['pysch'],
    },
  ],
};
