export const SET_LOADING = "SET_LOADING";
export const EMPTY_QUESTIONS = "[question] EMPTY_QUESTIONS";
export const SET_QUESTIONS = "[question] SET_QUESTIONS";
export const UPDATE_QUESTIONS = "[question] UPDATE_QUESTIONS";
export const VOTE_QUESTIONS = "[question] VOTE_QUESTIONS";
export const SET_SEARCH_TERM = "[question] SET_SEARCH_TERM";
export const FETCH_QUESTION_CATEGOREIS_FAILED =
  "[question] FETCH_QUESTION_CATEGOREIS_FAILED";
export const FETCH_QUESTION_CATEGOREIS_SUCCESS =
  "[question] FETCH_QUESTION_CATEGOREIS_SUCCESS";

export const SAVE_QUESTION_CATEGOREIS_FAILED =
  "[question] SAVE_QUESTION_CATEGOREIS_FAILED";
export const SAVE_QUESTION_CATEGOREIS_SUCCESS =
  "[question] SAVE_QUESTION_CATEGOREIS_SUCCESS";

export const FETCH_SIMILAR_QUESTIONS_SUCCESS =
  "[question] FETCH_SIMILAR_QUESTIONS_SUCCESS";
